version: '3.7'

x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
  image: sasaplus1/www
  init: true
  volumes:
    - .:/var/www

services:
  build:
    <<: *base
    command:
      - hugo
  new:
    <<: *base
  serve:
    <<: *base
    ports:
      - '1313:1313'
  sh:
    <<: *base
    command:
      - sh
    tty: true
