name: audit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - uses: treosh/lighthouse-ci-action@v2
        if: github.event_name == 'push'
        with:
          configPath: .lighthouserc.json
          urls: |
            https://www.sasaplus1.com
      - uses: treosh/lighthouse-ci-action@v2
        if: github.event_name == 'pull_request'
        with:
          configPath: .lighthouserc.json
          urls: |
            https://deploy-preview-${{ github.event.pull_request.number }}--sasaplus1-www.netlify.com
      - uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: .lighthouseci
