name: test

on:
  - push
  - pull_request

jobs:
  test:
    name: test
    strategy:
      matrix:
        node:
          - 12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run build
      - uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: .lighthouserc.json
      - uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: .lighthouseci
